name: Deploy Gradio App to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Or whichever branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Hugging Face
      run: huggingface-cli login --token ${{ secrets.hf_token }}

    - name: Push to Hugging Face Space
      run: huggingface-cli repo upload . --repo-id <sabahatatta>/<MoMGenerator> --branch main
